# Generated by Django 2.2 on 2021-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('poster', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('level', models.CharField(blank=True, max_length=40, null=True)),
                ('score', models.CharField(blank=True, max_length=40, null=True)),
                ('duration', models.CharField(blank=True, max_length=40, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('stars', models.CharField(blank=True, max_length=100, null=True)),
                ('story', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('score', models.CharField(max_length=40)),
                ('review', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'movie_pal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('score', models.CharField(max_length=40)),
                ('review', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'movie_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'movie_user',
                'managed': False,
            },
        ),
    ]
